---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    yum: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present
  - name: clone a repo
    git: repo=https://github.com/praveenkarra83/myfinalprojetAnsibledockerfile.git dest=/tmp/mygitrepo
  - name: build docker file
    command: chdir=/tmp/mygitrepo docker build -t addressbook:ansible .
  - name: Run the image to create container
    command: docker run -itd -P addressbook:ansible
